file_paths:
  gpac_master:
    file: "C:/Users/dhanv/OneDrive/Desktop/GPAC Master V5.xlsx"
    sheets:
      product_mapping: " GPAC Master Product Type"
      client_product_type_mapping: "Client_Product_Type Mapping"

  input_data: "C:/Users/dhanv/OneDrive/Desktop/TBR_testing_data.csv"

tagging_priority:
  client_product_code:
    enabled: true
    column_name: "CLIENT_PRODUCT_TYPE"

  keyword_attribute_country_combination:
    enabled: true
    apply_order: ["keyword_matching"]

column_priority:
  primary_columns:
    - "CD_INSTMT_TYPE"
    - "CLIENT_ASSET_CLASS"
    - "CLIENT_PRODUCT_TYPE"
    - "CLIENT_ASSET_CLASS_NAME"
    - "CLIENT_ASSET_SUBCLASS_NAME"
  fallback_columns:
    - "DESC_INSTMT"
    - "ISSUE_COUNTRY"
    - "ASSET_CURRENCY"
    - "ASSET_REGION_NAME"
    - "KNOWLEDGE_EXPERIENCE"
    - "ISLAMIC_PRODUCT"
    - "NON_DELIVERABLE"
    - "PARTICIPATION_CERTIFICATE"

keyword_matching:
  frequency_threshold: 1  # Lowered to 1 to ensure keyword sensitivity for testing
  stop_words: ["is", "for", "like", "on", "and", "the", "in"]

attribute_mapping:
  enabled: false  # Disable attribute mapping

country_mapping:
  enabled: false  # Disable country mapping

tagging_columns:
  - "GPAC_Product_Level1"
  - "GPAC_Product_Level2"
  - "GPAC_Product_Level3"

logging:
  log_file: "tagging_process.log"
  level: "INFO"
