
# === GPAC Tagging System Configuration ===
# This config file includes tagging priority logic, with Client Product Code tagging prioritized,
# followed by a Keyword and Attribute-Country combination. All fields and columns are defined here.

file_paths:
  gpac_master: "/Users/dnamas5/Downloads/GPAC Master V5.xlsx"  # Path to GPAC Master file containing mappings and rules.
  country_mapping: "/Users/dnamas5/Downloads/GPAC Master V5 - Country Mapping.csv"  # Country-specific mapping file.
  input_data: "/Users/dnamas5/Downloads/Dhanvi_Tagging_Data.csv"  # Input data file for tagging.
  output_file: "/Users/dnamas5/Downloads/0811V4_ClientProductType.csv"  # Output file for tagged data.
  log_file: "/Users/dnamas5/Downloads/TaggingLogFile.log"  # Log file for processing logs.

# ========================================
# TAGGING PRIORITY CONFIGURATION
# ========================================
tagging_priority:
  client_product_type:
    enabled: true  # Set to true to apply Client Product Code tagging as the first priority.
    column_name: "Keyword"  # Column name in the input data that corresponds to Product Code tagging.

  keyword_attribute_country_combination:
    enabled: true
    apply_order: ["keyword_matching", "attribute_mapping", "country_mapping"]
    # Notes:
    # - The sequence in apply_order determines the order in which keyword, attribute, and country mapping are applied.
    # - This order is customizable if adjustments are needed to prioritize one method over another.

# ========================================
# COLUMN PRIORITY CONFIGURATION
# ========================================
column_priority:
  primary_columns:
    - "CLIENT_PRODUCT_TYPE"
    - "CD_INSTMT_TYPE"
    - "HEDGE_FUND_STRATEGY"
  pattern_based_columns:
    patterns:
      - "^CLIENT_SEC_TYPE\d*$"  # Matches CLIENT_SEC_TYPE, CLIENT_SEC_TYPE2, CLIENT_SEC_TYPE3, etc.
      - "^SEDOL(_\w+)*$"  # Matches SEDOL, SEDOL_CODE, SEDOL_COUNTRY, SEDOL_CURRENCY
      - "^UNDERLYING_ID(_\w+)*$"  # Matches UNDERLYING_ID, UNDERLYING_ID_TYPE, UNDERLYING_DESCRIPTION
      - "^SP_RATING_(LONG|SHORT)$"  # Matches SP_RATING_LONG, SP_RATING_SHORT
      - "^MOODY_RATING_(LONG|SHORT)$"  # Matches MOODY_RATING_LONG, MOODY_RATING_SHORT
      - "^FITCH_RATING_(LONG|SHORT)$"  # Matches FITCH_RATING_LONG, FITCH_RATING_SHORT
  fallback_columns:
    - "DESC_INSTMT"

# ========================================
# ATTRIBUTE COLUMNS CONFIGURATION
# ========================================
attribute_columns:
  - "ISSUE_COUNTRY"
  - "ASSET_CURRENCY"
  - "ASSET_REGION_NAME"
  - "RISK_COUNTRY"
  - "KNOWLEDGE_EXPERIENCE"
  - "ISLAMIC_PRODUCT"
  - "NON_DELIVERABLE"
  - "PARTICIPATION_CERTIFICATE"
  - "MATURITY_DATE"
  - "PRIVATE_EQTY_FUND_TYPE"
  - "FUND_OF_FUNDS"
  - "UCITS_SCOPE"
  - "COCOS"
  - "IRS_TYPE"
  - "CUSIP"
  - "ISIN"
  - "TKN"
  - "ASSET_IN_POS"
  - "BLOCK_CODE"
  - "CLOSE_DATE"
  - "COUPON"
  - "COUP_FREQ"
  - "ISSUER"
  - "PUT_CALL"
  - "EXERCISE_TYPE"
  - "FX_TRADE_CURRENCY"
  - "GLOBAL_ALT_ID"
  - "ASSET_STATUS"

# ========================================
# COLUMNS TO IGNORE CONFIGURATION
# ========================================
ignore_columns:
  - "PRODUCT_BUSINESS_CODE"
  - "CLIENT_ASSET_CLASS"
  - "CLIENT_ASSET_CLASS_NAME"
  - "CLIENT_ASSET_SUBCLASS_NAME"

# ========================================
# KEYWORD MATCHING CONFIGURATION
# ========================================
keyword_matching:
  frequency_threshold: 3
  stop_words: ["is", "for", "like", "on", "and", "the", "in"]
  # Notes:
  # - Adjust stop words and frequency threshold to optimize keyword sensitivity.

# ========================================
# ATTRIBUTE AND COUNTRY MAPPING
# ========================================
attribute_mapping:
  enabled: true
  fields:
    - "issuer_domicile"
    - "credit_rating"
    - "coupon_type"
    - "maturity"
    - "sector"
  # Notes:
  # - Add or remove fields as needed to reflect new attributes in GPAC.
